name: Cron Task

on:
  push:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build:
    name: Update Profile
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go mod tidy

      - name: Build & Run
        run: |
          go build . && ./wuhan005 && rm wuhan005

      - name: Update sponsors.svg
        run: |
          cd sponsorkit
          pnpm install
          pnpm run build
          mv -f sponsors.svg ../sponsors.svg
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: wuhan005

      - name: Git Commit
        run: |
          git config --local user.email "bot@github.red"
          git config --local user.name "Eggplant Bot"
          git add README.md sponsors.svg
          git commit -m "Update README.md" || true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
